/**-------------------------------------------------------------------------
* Nombre: infoCompbeneficiario
* @author Julio Medellin
* Proyecto: MW SB VTS - BBVA 
* Descripción : Clase wrapper para respuesta de petición Rest
* --------------------------------------------------------------------------
*                         Fecha           Autor                   Descripción
* -------------------------------------------------------------------
* @version 1.0           02/05/2019      Julio Medellin           Clase para mantener los registros Benificiario(wrap)*/
 public class infoCompbeneficiario {
        /* llamada a variable fechaNacimiento del objeto cotizador*/
        public String fechaNacimiento { get; set; }
        /* llamada a variable edad del objeto cotizador*/    
        public String edad { get; set; }
        /* llamada a variable sexoDelConductor del objeto cotizador*/	
        public String sexoDelConductor { get; set; }
        /* llamada a variable rfc del objeto cotizador*/
        public String rfc { get; set; }
        /* llamada a variable nacionalidad del objeto cotizador*/
        public String nacionalidad { get; set; }
        /* llamada a variable profesion del objeto cotizador*/
        public String profesion { get; set; }
        /* llamada a variable colonia del objeto cotizador*/
        public String colonia { get; set; }
        /* llamada a variable calleOAvenida del objeto cotizador*/
        public String calleOAvenida { get; set; }
        /* llamada a variable codigoPostal del objeto cotizador*/
        public String codigoPostal { get; set; }
        /* llamada a variable numeroExterior del objeto cotizador*/
        public String numeroExterior { get; set; }
        /* llamada a variable numeroInterior del objeto cotizador*/
        public String numeroInterior { get; set; }
        /* llamada a variable origen del objeto cotizador*/
        public String origen { get; set; }
        /* llamada a variable ciudad del objeto cotizador*/
        public String ciudad { get; set; }
        /* llamada a variable estado del objeto cotizador*/
        public String estado { get; set; }
        /* llamada a variable pais del objeto cotizador*/
        public String pais { get; set; }
        /* llamada a variable delegacion del objeto cotizador*/
        public String delegacion { get; set; }
    }