/**-------------------------------------------------------------------------
* Nombre: MX_SB_VTS_SMAR_consultaCarga_cls
* @author Arsenio Perez Lopez (xemo)
* Proyecto: MW SB VTS - BBVA
* Descripción : Clase de ayuda para el componente de envio de leads

* --------------------------------------------------------------------------
*                         Fecha           Autor                   Desripción
* -------------------------------------------------------------------
* @version 1.0           20/06/2019      Arsenio  Perez            Creación
* --------------------------------------------------------------------------*/
global class MX_SB_VTS_SMAR_consultaCarga_cls implements iaso.GBL_Integration_Headers {
      /** */
     global HttpRequest modifyRequest(HttpRequest request) {
      return request;
    }
}