/**
 * @File Name          : WB_CTI_tst.cls
 * @Description        : 
 * @Author             : Eduardo Hernández Cuamatzi
 * @Group              : 
 * @Last Modified By   : Eduardo Hernández Cuamatzi
 * @Last Modified On   : 7/8/2019 11:43:29
 * @Modification Log   : 
 *==============================================================================
 * Ver         Date                     Author      		      Modification
 *===========================s===================================================
 * 1.0    20/6/2019 17:46:29   Eduardo Hernández Cuamatzi     Initial Version
 * 1.1    31/7/2019 13:11:27	Eduardo Hernández Cuamatzi     Mejora credenciales CTI
**/
@isTest
private class WB_CTI_tst {
	
}