ExternalSectionID__c,Name,Nombre__c,NumeroSeccion__c
1,CS-00004,Ventas.Mide las Técnica telefónicas para el manejo de una llamada de Servicio o Venta.,4
1,CS-00001,Reglas del Juego.Revisa los elementos regulatorios que contiene una llamada,1
1,CS-00003,Experiencia con el cliente.Mide el desempeño del analista hacia el cliente.,3
1,CS-00002,"Producto / Proceso. Califica el conocimiento de productos, proceso, términos y condiciones del negocio.",2
